### PR TITLE
Split GUI code to separate module

### PR DESCRIPTION
**Pull request by Runemoro**
This way, you can use Enigma as a library without having to include all the GUI, commands, and server code. Also makes it possible to add an Android front-end in the future.

The modules are:
 - `enigma`: Mappings, Analysis, Remapping, Decompiling, etc.
 - `enigma-swing`: Swing front-end
 - `enigma-server`: Server front-end
 - `enigma-cli`: Command line front-end

### CODE REVIEW

**Comment by liach** [comment]
Mind keep main enigma code in the root project than in the `:enigma` subproject to reduce diffs?

**Comment by Runemoro** [comment]
@liach I'm not sure how to make the subprojects depend on the root project. By default the root project depends on all subproject, and adding root as a dependency for subprojects throws a circular dependency error.

It might be possible to fix it, but I think this would be doing the opposite of how Gradle subprojects are meant to be used (root depends on libraries defined in subproject, rather than subprojects depend on root).

The history on Github [seems to be ok](https://github.com/Runemoro/Enigma/blame/modules/enigma/src/main/java/cuchaz/enigma/analysis/ClassCache.java), though.

**Comment by liach** [comment]
I think `implementation parent` should work `implementation project.parent`

**Comment by Prospector** [comment]
Yes! I don't understand Enigma enough to review this but I am very happy to see this...maybe I can continue work on Enigma-JFX after this is merged.

**Comment by liach** [comment]
Also keeping the core code in the root project's src folder can maintain compatibility with at least some of the existing prs.

**Comment by modmuss50** [comment]
Does this still include the fat shadow jar? Atleast for the CLI?

Stitch will also need updating.

**Comment by Juuxel** [comment]
@Runemoro You can depend on the root project with `implementation project(':')` (at least usually, not sure if something breaks it here)

**Comment by Runemoro** [comment]
@liach @Juuxel Gradle automatically makes the root project depend on all subprojects. Here, the `enigma` module should depend on nothing, it's the base module all of the others depend on.

Having subprojects depend on the root is the opposite of how Gradle is intended to work, see https://discuss.gradle.org/t/how-do-i-put-a-root-project-dependency-into-a-sub-project/7484/12.

**Comment by Runemoro** [comment]
> Does this still include the fat shadow jar? Atleast for the GUI?

Yes, there's a shadow-jar for `enigma-swing`.

**Comment by modmuss50** [comment]
Merge conflicts and then this should be good to merge.

**Pull request merged**
