### PR TITLE
Update all deps, remove usage of jcenter

### PR DESCRIPTION
**Pull request by modmuss50**
Proguard beta is re-hosted on the fabric maven as its not on central

### CODE REVIEW

**Comment by modmuss50** [comment]
oh of course gradle doesnt support JDK 16...

**Comment by modmuss50** [comment]
Moved actions back to run with jdk 15, dont fanncy running it on gradle 7.0-m3 even though I imagine it would be fine.

**Review by 2xsaiko — APPROVED** [review]
Do you want to bump the source/target compat to java 15 as well while you're at it? I certainly wouldn't complain :P

**Comment by modmuss50** [comment]
Not quite yet, I have an older PR for that. Need to re evaluate that

**Comment by Geolykt** [comment]
Why not Java 16 if one already wants to use Java 15?

**Comment by 2xsaiko** [comment]
Gradle doesn't support it yet

**Pull request merged**
