### PR TITLE
CFR support

### PR DESCRIPTION
**Pull request by Runemoro**
Add an `enigma:decompiler` service type and rewrites code that's hardcoded for Procyon, moving all Procyon-specific code to a `enigma:procyon` service, allowing us to implement support for more decompilers in the future.

Adds support for CFR.

### CODE REVIEW

**Comment by liach** [comment]
You can add a plain procyon decompiler that uses its literal output (like call pathway of command line procyon), which afaik works for `LivingEntity`

**Comment by Runemoro** [comment]
@liach How would it build the source index?

**Comment by leibnitz27** [comment]
CFR author here - this makes heavy use of non stable interfaces, and will lock you to one specific version of CFR. 

Please use interfaces demonstrated in cfr_client toy project, and discussed at https://www.benf.org/other/cfr/api

**Comment by modmuss50** [comment]
Looks good, its too much work for me to do a full indepth review, I assume its fine. If there are any bugs those can easily be fixed later.

**Pull request merged**
