### PR TITLE
Added progress bar for saving

### PR DESCRIPTION
**Pull request by modmuss50**
This may not be wanted, but it does at least tell you once its finished saving instead of the program hanging for a few seconds.

I may look into some more issues on here.

### CODE REVIEW

**Comment by Thog** [comment]
Actually the saving system just need a rewrite. Also, the progress bar is slowing the saving process apparently...

**Comment by modmuss50** [comment]
Yes thats what I did...

**Comment by modmuss50** [comment]
Oh wait I read that wrong

**Comment by Thog** [comment]
Because of the rewrite of the save system, this PR doesn't need to be merged anymore.

**Pull request closed without merging**
