### PR TITLE
Update cfr and fixes a few related issues

### LINKED ISSUE #368: Clicking items in the call graph does not take you to the usage
Related to #367, clicking items in the call graph doesn't take you to the actual line. It opens the containing class, but leaves you at the very top, and if the class is already open nothing happens at all.
image

### PR DESCRIPTION
**Pull request by liach**
fixes #368 context for token references, missing some field and method references

depends on https://github.com/FabricMC/cfr/pull/6

### CODE REVIEW

**Comment by liach** [comment]
Drafting as the ci will not pass unless the cfr pr is merged and a build is done.

**Comment by liach** [comment]
Now cfr still has the local var carry over and token references don't work well in lambdas.

**Comment by liach** [comment]
@modmuss50 This one should be ready and cover most of the previously noticed cfr issues. If you have other noticed issues, feel free to tell me and I will test it out.

**Comment by liach** [comment]
For people who want to test:
1. Clone cfr (my branch) locally, and run `./gradlew publishToMavenLocal`
2. Clone enigma (this branch) locally, edit the cfr version in `enigma/build.gradle` to `0.0.6+local` than `0.0.6`, and run `./gradlew publishToMavenLocal`
3. Open yarn. In the `build.gradle`'s `buildscript`'s nested `repositories` block, add a line `mavenLocal()`. In the `gradle.properties`, change `enigma_version` to `1.3.2+local`. Then run `./gradlew yarn` or `yarnU` and see the difference/find other problems.

**Review by 2xsaiko — APPROVED** [review]
LGTM! Will merge once the cfr changes are merged.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
