### PR TITLE
Adds a red highlight for overridden methods in method inheritance tree gui

### PR DESCRIPTION
**Pull request by liach**
image
Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by asiekierka** [comment]
As discussed in chat, please use a green-ish color or bold/italic over red (which implies an error).

**Comment by liach** [comment]
image
Green and italic here.

**Comment by JamiesWhiteShirt** [comment]
I would suggest not using green nor red. Green is positive and red is negative. This represents neither. Perhaps we could use the icons instead? Italics and/or bold should be fine too.

**Comment by Earthcomputer** [comment]
Also that green is a little hard to read on a white background

**Comment by gegy1000** [comment]
Could potentially just be italics -- with https://github.com/FabricMC/Enigma/commit/924ab1cfe379d5744d5c864b3236934a037a21ae irrelevant entries will be hidden altogether.

**Comment by InsomniaKitten** [comment]
A gutter icon would be more appropriate for this, with a distinction between overrides and abstract implementations.

**Comment by liach** [comment]
@gegy1000 How is the new look? 
image
The gray italic names are parents with no actual inheritance content.

**Comment by gegy1000** [comment]
Looks great! This ready for merge?

**Comment by liach** [comment]
Definitely.

**Comment by liach** [comment]
Please squash merge as I have too many commits, btw.

**Pull request merged**
