### PR TITLE
Makes sure save mappings is completed before next action

### LINKED ISSUE #407: Pressing "save" in the close confirmation dialog doesn't save changes
To reproduce:
- Open a jar and a mapping set in Enigma (eg. with `gradlew yarn`)
- Rename something
- Press the window's close button without saving beforehand
- When the confirmation dialog about unsaved changes appears, choose "Save"
- Your changes won't be saved.

### PR DESCRIPTION
**Pull request by liach**
Fixes #407

Not yet tested

### CODE REVIEW

**Comment by YanisBft** [comment]
Clicking on "save" in the confirmation dialog now freezes completely Enigma

**Comment by liach** [comment]
Yeah, this is a fun story. Fixed, and added documentation to prevent such code errors in the future. Requesting another review from yanis.

**Review by YanisBft — APPROVED** [review]
awesome!

**Review by Juuxel — APPROVED** [review]

**Review by 2xsaiko — APPROVED** [review]

**Comment by liach** [comment]
@modmuss50 mind check out this quick fix and other fixes on cfr, which is effectively our only decompiler, as procyon is still wip for higher java?

**Comment by liach** [comment]
Hmm, @modmuss50 mind check this one? If this one is good, I think we can integrate this and make another minor release of enigma.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
