### PR TITLE
Patch StackEmptyException thrown in some cases

### PR DESCRIPTION
**Pull request by alexjmeech**

### CODE REVIEW

**Comment by liach** [comment]
Any example thrown exception stack traces?

**Comment by alexjmeech** [comment]
It happens every time when I try to export the 1.14.4 server as source using the mojang proguard mapping. I was able to get it to stop crashing with this fix, although it still seems to deadlock towards the end.

**Comment by liach** [comment]
Hmm, it does happen to me and happens for `KeySet` `InverseEntrySet`, and `SubmapIterator` classes. Maybe proguard removed the outer classes of these classes. Imo we should emit a warning when encountering these classes.

**Comment by 2xsaiko** [comment]
Fixed, see #262

**Pull request closed without merging**
