### PR TITLE
[WIP] Mapping rework

### PR DESCRIPTION
**Pull request by gegy1000**
This PR refactors the mapping storage and entry code. This increases consistency by unifying a lot of previously scattered logic. The improvement can be seen in terms of lines of code with ~1000 lines removed.

This will hopefully make maintenance easier in the future. Currently this PR just needs to be tested to make sure it doesn't create any damaging issues.

Apologies for the large PR -- I can write a detailed description of what changed if needed. 😄

### CODE REVIEW

**Comment by asiekierka** [comment]
Here's a good question.

How on earth do we even begin testing this before we push it? :D

**Comment by gegy1000** [comment]
Was thinking of doing PRs to Yarn with it and checking those, but that'd cause issues with everyone else as child mappings get discarded. I can only imagine it'd have to be tested on a fork and hopefully stable enough before a snapshot is released for that to be merged in.

**Comment by asiekierka** [comment]
I think the best route will be to simply move Yarn to it for 19w03a and forward, and hope nothing breaks - people can probably stay on 19w02a for a bit just in case

**Comment by asiekierka** [comment]
Actually...

Can we put https://github.com/FabricMC/Enigma/pull/91/commits/7f59e51485d1197161847fd622264f588ca20db5 behind an in-code flag? That way, for a while, both Enigmas should be compatible

**Comment by gegy1000** [comment]
That could potentially cause issues as new Enigma would not propagate remapped entries. Anyway, gotta get back into this. There are some issues that I need to fix before this will be ready.

**Comment by asiekierka** [comment]
>That could potentially cause issues as new Enigma would not propagate remapped entries.

Ah, in this case that is fair.

**Comment by gegy1000** [comment]
As far as I can tell, this PR should be ready. Will test it a bit more first, though.

**Pull request merged**
