### PR TITLE
Feature/weave

### PR DESCRIPTION
**Pull request by liach**
#137 plus moving weave write tiny command to enigma. Closes FabricMC/weave#2

### CODE REVIEW

**Comment by asiekierka** [comment]
Don't move write tiny to Enigma yet, as I said. Sorry.

**Comment by liach** [comment]
@asiekierka removed weave stuff.

**Comment by JamiesWhiteShirt** [comment]
It's worth mentioning that this PR fixes the build. The changes from the last PR ended up failing tests. Would be nice to have this in so we can start checking mappings in yarn properly.

**Comment by gegy1000** [comment]
Looks great, is this good to merge?

**Comment by liach** [comment]
Yes please @gegy1000

**Pull request merged**
