### PR TITLE
Improve stats gen to show percentages

### PR DESCRIPTION
**Pull request by modmuss50**

### CODE REVIEW

**Comment by gegy1000** [comment]
Is this ready to merge?

**Comment by 2xsaiko** [comment]
I still have an open PR in modmuss's repo for this: https://github.com/modmuss50/Enigma/pull/1

**Comment by modmuss50** [comment]
ah, ill take a look. sorry I tottaly missed it.

**Comment by modmuss50** [comment]
merged into mine, should be good to merge here now.

**Pull request merged**
