### PR TITLE
Added theme switcher + dark theme

### PR DESCRIPTION
**Pull request by modmuss50**
java_2017-06-04_18-28-09

That is a screenshot of the dank theme I can up with based off the color pallet found here: https://github.com/dracula/dracula-theme

Feel free to suggest improvements to the theme or suggest new ones.

### CODE REVIEW

**Comment by modmuss50** [comment]
Uhh, git is broke. It might be ok with a squish + merge.

**Comment by unascribed** [comment]
This would be even better if the entire UI was restyled, instead of just the code pane.

Are there any good dark LaFs for Swing?

**Comment by modmuss50** [comment]
The one I tried, https://github.com/bulenkov/Darcula (used by idea I assume) worked with mixed results. The main issue is that it's not the native look. When I'm back at my PC next I will get you a screen shot of it.

**Comment by lclc98** [comment]
The problem is the Syntax pane uses it's own colors
image

**Comment by modmuss50** [comment]
No that's not the issue, the colours can be set to fit with the LAF. The issue I had with it was things like the file dialogs aren't the native ones, and the tabs at the top right look a tad off. I could easily add it as a config setting if people wanted?

**Comment by modmuss50** [comment]
Im not 100& sure what you mean by `real singleton`, I have fixed the other issues I think.

**Comment by unascribed** [comment]
JFileChooser in general is a bad choice for a file dialog. Any LaF other than the GTK+ one on Linux gives you this nigh-unusable pile of garbage, and even on other platforms it's just Swing pretending to be the native dialog.

Use AWT's FileDialog to always get the native one, and then you can use whatever LaF you want.

**Comment by modmuss50** [comment]
Ok, should this PR be merged? Or shall I add a setting for the dark LAF? along with changing all the file choosers over to AWT. Or shall that happen in another PR?

**Comment by unascribed** [comment]
AWT file dialogs are probably out of scope for this PR (in my opinion), and since alternate LaFs break JFileChooser, I'd say this pull is good as-is. A separate PR could add the dark LaF and switch over to FileDialog.

**Pull request merged**
